### ISSUE TITLE
 "502 Bad Gateway" Error in Demo

### ISSUE THREAD

**Issue by X1AOX1A** [SunzeY/AlphaCLIP#10]
"502 Bad Gateway" Error in [Huggingface Demo](https://huggingface.co/spaces/Zery/Alpha_CLIP_ImgVar) and [OpenXLab Demo](https://openxlab.org.cn/apps/detail/SunzeY/Alpha-CLIP_Image_Var1)

**Comment by SunzeY** [comment]
We have relaunched Demo, it is.working right now. Currently,  OpenXLab is not very stable. we will fix that later.

**Comment by X1AOX1A** [comment]
> We have relaunched Demo, it is.working right now. Currently, OpenXLab is not very stable. we will fix that later.

I want to thank you for relaunching it, but the Huggingface Demo crashed again.
<img width="1107" alt="Screenshot 2023-12-19 at 19 51 32" src="https://github.com/SunzeY/AlphaCLIP/assets/52992366/f2b51585-3183-44d7-857d-804c4f43858b">

**Comment by SunzeY** [comment]
The hugging-face demo is only a web page with openxlab demo plugin, you can go to openxlab demo to restart it.
By the way, the demo code is available in `demo`, you can use that demo to create local app. As hugging-face A10 is too expensive for us to show demo.

**Comment by X1AOX1A** [comment]
Thanks for the update. I'll check out the OpenXLab demo as suggested. Cheers!
