### ISSUE TITLE
question about the alpha-clip combined with LLaVA-7b

### ISSUE THREAD

**Issue by xinli2008** [SunzeY/AlphaCLIP#14]
Sorry to bother you in your busy time and i am hurry to cary out alpha-clip with LLaVA-7b-clip.
I followed the instructions in [here](https://github.com/SunzeY/AlphaCLIP/issues/11#issuecomment-1862643961) and changed something.
The input images and masks are as follows:
![image](https://github.com/SunzeY/AlphaCLIP/assets/71311087/c7a95f46-5938-4822-ab68-5d50ca04646b)
![image](https://github.com/SunzeY/AlphaCLIP/assets/71311087/5f31214a-2659-4578-b43a-0a6ad8dc98df)
and the rewrited forward are as follows:
![image](https://github.com/SunzeY/AlphaCLIP/assets/71311087/5d0cfa4e-1a40-4eaa-8901-852b484a009f)
But the generated text doesn't seems to be a specific area of concern and i am wondering why. can you give me some useful advice?
Thank you

**Comment by xinli2008** [comment]
And I tried another methods, given a original image and mask image (mode is L), i combine them to alpha image. 
the combined image and changed rewrited forward are as follows:
![image](https://github.com/SunzeY/AlphaCLIP/assets/71311087/029806e3-76b1-410d-b743-2f0e4cf8011a)
![image](https://github.com/SunzeY/AlphaCLIP/assets/71311087/becffb74-3c4c-4f9d-87a5-39877c101b02)

And my prompt is : Describe this image and its style in a very detailed manner.
The generated text is : The image features a large black and white dog with a smile on its face, likely a German Shepherd. The dog is the main focus of the image, taking up a significant portion of the frame. The dog appears to be enjoying a moment of happiness, possibly posing for a picture.
I don't think the results are too good, because he still seems to be paying attention to the black areas of the image.
Can you give me some useful advice?

**Comment by SunzeY** [comment]
Your mask transform should involve center_crop, same as llava preprocess does.

**Comment by xinli2008** [comment]
thank you for your kindly reply~! I try that method, unfortunately, it does not work
without transform.centercrop, the visualized image and mask are as follows:
![image](https://github.com/SunzeY/AlphaCLIP/assets/71311087/c7e35b29-f7bd-4d57-9647-b13ea5f881b6) ![image](https://github.com/SunzeY/AlphaCLIP/assets/71311087/bc540601-8498-41ae-8d39-9507ae476777)
The mask area is correctly mapped to the original image, but the generated text is consistent with the result without Alpha-clip

**Comment by XuRui314** [comment]
Is this problem solved? Maybe LLaVA need to be fine tuned to match alpha clip's output?

**Comment by xinli2008** [comment]
No! we suspect that alpha-clip is a mechanism of attention. As in the image above, this is more difficult when the main body of the image is a banana and we want to use alpha-clip to texture the background area；
Good luck

**Comment by XuRui314** [comment]
I did encounter this problem when using my own model(LLMs are Vicuna and GLM): 
"But the generated text doesn't seems to be a specific area of concern and i am wondering why. can you give me some useful advice?"
Since the paper mentioned they finetuned LLaVA 1.5 with alpha clip, so i doubt the zero shot stitching ability of alpha clip

**Comment by xinli2008** [comment]
Depending on the image, it may be when the subject of the image is more obvious, and we try to ignore the subject completely, which may be difficult to do with the alpha-clip with LLaVA.

**Comment by SunzeY** [comment]
hi, I believe your case work in some degree when using Alpha-CLIP
![case1](https://github.com/SunzeY/AlphaCLIP/assets/76475229/054c599d-b73c-462e-948e-d5bc35ba4dcb)
![case2](https://github.com/SunzeY/AlphaCLIP/assets/76475229/c77535dd-4835-456e-96bc-f802e8b5166b)
The official demo is now available now! you can checkout on your own.

**Comment by XuRui314** [comment]
> hi, I believe your case work in some degree when using Alpha-CLIP ![case1](https://private-user-images.githubusercontent.com/76475229/293011237-054c599d-b73c-462e-948e-d5bc35ba4dcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NzM5MzQsIm5iZiI6MTcwMzY3MzYzNCwicGF0aCI6Ii83NjQ3NTIyOS8yOTMwMTEyMzctMDU0YzU5OWQtYjczYy00NjJlLTk0OGUtZDViYzM1YmE0ZGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDEwNDAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkYjE3NWQ4NDU2Yjk4OTU4YjRkZmQ1NzgwOGMxNWZmOGMwNzhjOTU1MWQyYTQwMTlhOWQ5ZmY1N2RlYWI3NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JsWhgH0eT2cD4R8f_9KUiU-DbzWG2YQ2eHKivdT7SRI) ![case2](https://private-user-images.githubusercontent.com/76475229/293011288-c77535dd-4835-456e-96bc-f802e8b5166b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NzM5MzQsIm5iZiI6MTcwMzY3MzYzNCwicGF0aCI6Ii83NjQ3NTIyOS8yOTMwMTEyODgtYzc3NTM1ZGQtNDgzNS00NTZlLTk2YmMtZjgwMmU4YjUxNjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDEwNDAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZWVkOTA1NWNiYTY4NGVjOTE3NmY0ZTc1NWFiNzM4NDUyMTEwMmQ0N2I2ZmRjY2IyMDQ0YmRlNDFhMGNmMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CqZ8d5yl-tqOUKIyG0NHY02oAM-bJ7ODhklTLZ-roUM) The official demo is now available now! you can checkout on your own.

Thanks for sharing the demo. May i ask if it's necessary to fine tune Alpha clip when stitching to a new MLLM? As for me, the zero shot stitching works not well.

**Comment by SunzeY** [comment]
Our demo doesn't involve finetuning of LLaVA. It only involve replacing original CLIP with Alpha-CLIP. the code is also available in `demo/with_llm`. I believe a bit finetuning can help you get better result.

**Comment by XuRui314** [comment]
Thanks for replying :)
