### ISSUE TITLE
 AttributeError: 'NoneType' object has no attribute 'from_pretrained' 

### ISSUE THREAD

**Issue by justinday123** [SunzeY/AlphaCLIP#15]
when i use diffusion, ' AttributeError: 'NoneType' object has no attribute 'from_pretrained'  ' occurs.

model, vis_preprocess, txt_preprocess = load_model_and_preprocess("blip_diffusion", "base", device=device, is_eval=True

what is the problem?

**Comment by SunzeY** [comment]
You should checkout [LAVIS](https://github.com/salesforce/LAVIS), make sure BLIP-Diffusion original code is runnable, than test with our demo.
