### ISSUE TITLE
The Alpha-clip demo with LLAVA will constantly repeat a sentence under certain specific images.

### ISSUE THREAD

**Issue by didiforgithub** [SunzeY/AlphaCLIP#20]
Just like this. I would like to understand why this situation occurs. 
![1](https://github.com/SunzeY/AlphaCLIP/assets/84363704/740387c3-d052-4194-b37d-67b611e63f6f)

**Comment by SunzeY** [comment]
Hi, this image is too difficult for LLaVA to understand and LLaVA itself have similar case like circular duplication. A straightforward solution is to increase duplication penalty during beam search.

**Comment by didiforgithub** [comment]
Thanks
