### ISSUE TITLE
The magic number of 1.9231 and 6

### ISSUE THREAD

**Issue by Wangt-CN** [SunzeY/AlphaCLIP#28]
Dear author @SunzeY,

Thanks a lot for this great work! By going through the code, may I ask what is the role of the magic number 6 and 1.9231 when constructing the mask? https://github.com/SunzeY/AlphaCLIP/blob/3e7cdd7b417fc27bc527f8dbce54b5f2f0891e0f/demo/with_llm/app.py#L151

**Comment by lxysl** [comment]
@SunzeY @Aleafy Any explanation to this issue? Thanks.
