### ISSUE TITLE
Annotations of the generated Imagenet

### ISSUE THREAD

**Issue by callsys** [SunzeY/AlphaCLIP#29]
Thank you for your great work!
Will the annotations (mask, caption) of ImageNet generated by the data generation pipeline proposed in this paper be open source soon? I would appreciate it if you could provide it.

**Comment by SunzeY** [comment]
It is currently difficult for us to share all the annotation on whole ImageNet on huggingface(as each mask need quite amount of storage). We are considering compress the number of images or first launching pseudo annotation on ImageNet-1k

**Comment by callsys** [comment]
Thanks!
