### ISSUE TITLE
Fail to download clip_l14_grit+mim_fultune_6xe.pth

### ISSUE THREAD

**Issue by donggoing** [SunzeY/AlphaCLIP#37]
![image](https://github.com/SunzeY/AlphaCLIP/assets/29890210/aa5d90e5-972f-4b68-a116-f00c5ad0a88d)

**Comment by SunzeY** [comment]
There exists bugs in openxlab. I recommend using gogle-drive link if openxlab checkpoint is not available

**Comment by donggoing** [comment]
Ok. Thanks
