### ISSUE TITLE
use Text prompt to get SAM mask

### ISSUE THREAD

**Issue by onefish51** [SunzeY/AlphaCLIP#4]
great work!

I see the graph 
![image](https://github.com/SunzeY/AlphaCLIP/assets/21029719/c10944e9-85ce-408d-8d36-61b61f4b2f29)
Does it mean that using a text prompt effectively generates the SAM mask by AlphaCLIP ?

[Text prompt? #4](https://github.com/facebookresearch/segment-anything/issues/4)
>We believe directly using the text from text features from CLIP is not good. Because the explainability of CLIP is bad. Using the text features matched with opposite semantic regions lead to wrong results.
![image](https://github.com/SunzeY/AlphaCLIP/assets/21029719/5cb00e64-33b3-4b23-87be-904bc77b7e61)

As it shown the original approach of exclusively deriving the SAM mask from the text prompt did not produce desired outcomes.

**Comment by SunzeY** [comment]
Hi, sorry for confusing figure. It's only a SUPPER simplified figure to show our annotation pipeline. Actually, We use SAM for auto mask generation (with 16 points per side) to generate tens of mask per image, then we use Alpha-CLIP to score these masks(as masked images with background set to a pure color) with ground truth image level label. in the end we rank these masks and get top scored mask as our pseudo-labeled images.
Alpha-CLIP cannot generate any dense label directly. As SAM doesn't support CLIP feature as condition in their released code either!

**Comment by onefish51** [comment]
I see [SAM-CLIP: Merging Vision Foundation Models towards Semantic and Spatial Understanding](https://arxiv.org/abs/2310.15308) and [Text2Points to guide SAM](https://github.com/xmed-lab/CLIP_Surgery) .  I guess alphaclip  can do better !

**Comment by SunzeY** [comment]
Hi, thanks for sharing these frontier works with us! We also believe Alpha-CLIP work better in these scenarios for that patch level feature pooling is too coarse for small object!
