### ISSUE TITLE
ViT-B/32 Model

### ISSUE THREAD

**Issue by ksa0910** [SunzeY/AlphaCLIP#5]
Do you have plans to release a model that uses ViT-B/32 embeddings?

**Comment by SunzeY** [comment]
We don't have plans to do this. In our experiment. We find it difficult to train Vit-B/32 model with an improved accuracy on ImageNet-S zero-shot classification. We only observe improvement in ViT-B/16, ViT-L/14, ViT-L/14@336 as the absolute improvement also increase with **model capacity and resolution**, which is interesting, but not surprising. So, we suggest using as big model as you can to test both Alpha-CLIP and original CLIP.
