### ISSUE TITLE
When will release the training code of alpha-CLIP? 忍不住问了。

### ISSUE THREAD

**Issue by LinQianhe02grey** [SunzeY/AlphaCLIP#51]
Please,big good bro.I want to have a try about clip,I think your project is the best game.Thank you,thank you.
您好，非常感谢您的工作，请问最近能否公布一下训练代码？

**Comment by SunzeY** [comment]
We have launched training code as well as our data. Sorry for keep you waiting for so long.

**Comment by LinQianhe02grey** [comment]
Thank you.You are the best.
