### ISSUE TITLE
Masked image for classification

### ISSUE THREAD

**Issue by zhiheLu** [SunzeY/AlphaCLIP#6]
Thanks for your great work. 

Given the mask of interest and the image, the intuitive idea is to mask the unrelated regions in the image for classification, which should be useful. Have you tried this?

**Comment by SunzeY** [comment]
We believe directly mask unrelated regions with a pure color can greatly damage classification accuracy (like being point out by [MaskAdaptedCLIP](https://github.com/facebookresearch/ov-seg)) as this will lose valuable context information. Check out their paper and our paper's related work for detailed explanation！
