### ISSUE TITLE
will you consider using the eva-clip-g model to get an eva-clip-g version of Alpha-CLIP?

### ISSUE THREAD

**Issue by XuRui314** [SunzeY/AlphaCLIP#9]
Excellent work, congratulations, will you consider using the eva-clip-g model to get an eva-clip-g version of Alpha-CLIP?

**Comment by SunzeY** [comment]
Thank you for you attention. We are not considering doing this now. Currently, we only have plans to train based on open_clip repo to CLIP-G. EVA training involve mask token prediction, which for now we haven't got a good idea to make region level contrastive learning to fit in.
